export const LABELS = {
  SESSION: "lab.session",
  PROJECT: "lab.project",
  CONTAINER: "lab.container",
} as const;

export const VOLUMES = {
  WORKSPACES: "lab_session_workspaces",
  OPENCODE_AUTH: "lab_opencode_auth",
  OPENCODE_AUTH_TARGET: "/root/.local/share/opencode",
  BROWSER_SOCKET_DIR: "/tmp/agent-browser-socket",
} as const;

export const TIMING = {
  CONTAINER_MONITOR_RETRY_MS: 5000,
  OPENCODE_MONITOR_RETRY_MS: 5000,
  OPENCODE_SYNC_INTERVAL_MS: 30_000,
  CONTAINER_MONITOR_INITIAL_RETRY_MS: 1000,
  CONTAINER_MONITOR_MAX_RETRY_MS: 60_000,
  COMPLETION_DEBOUNCE_MS: 5000,
  SERVICE_WAIT_TIMEOUT_MS: 30_000,
  SERVICE_WAIT_INTERVAL_MS: 250,
  POOL_RECONCILIATION_TIMEOUT_MS: 120_000,
  POOL_BACKOFF_BASE_MS: 1000,
  POOL_BACKOFF_MAX_MS: 30_000,
  OAUTH_STATE_EXPIRY_MS: 600_000,
} as const;

export const LIMITS = {
  LOG_BUFFER_SIZE: 500,
  LOG_LINES_PER_SECOND: 100,
  RATE_LIMITER_WINDOW_MS: 1000,
  SUMMARY_FALLBACK_LENGTH: 200,
  FRAME_MIN_INTERVAL_MS: 100,
} as const;

export const SERVER = {
  IDLE_TIMEOUT_SECONDS: 255,
} as const;
