name: Publish Container Images

on:
  push:
    branches:
      - main
    paths:
      - "containers/**"

env:
  REGISTRY: ghcr.io
  IMAGE_PREFIX: ${{ github.repository_owner }}/lab

jobs:
  list-containers:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.list.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4

      - id: list
        run: |
          containers=$(ls -d containers/*/ \
            | xargs -n1 basename \
            | jq -R -s -c 'split("\n") | map(select(length > 0))')
          echo "matrix=${containers}" >> "$GITHUB_OUTPUT"

  build:
    needs: list-containers
    if: needs.list-containers.outputs.matrix != '[]'
    strategy:
      matrix:
        container: ${{ fromJson(needs.list-containers.outputs.matrix) }}
        arch: [amd64, arm64]
        include:
          - arch: amd64
            runner: ubuntu-24.04
          - arch: arm64
            runner: ubuntu-24.04-arm
    runs-on: ${{ matrix.runner }}
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v6
        with:
          context: containers/${{ matrix.container }}
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_PREFIX }}/${{ matrix.container }}:main-${{ matrix.arch }}
          cache-from: type=gha,scope=${{ matrix.container }}-${{ matrix.arch }}
          cache-to: type=gha,mode=max,scope=${{ matrix.container }}-${{ matrix.arch }}

  merge-manifest:
    needs: [list-containers, build]
    if: needs.list-containers.outputs.matrix != '[]'
    strategy:
      matrix:
        container: ${{ fromJson(needs.list-containers.outputs.matrix) }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create multi-arch manifest
        run: |
          docker buildx imagetools create \
            -t ${{ env.REGISTRY }}/${{ env.IMAGE_PREFIX }}/${{ matrix.container }}:main \
            ${{ env.REGISTRY }}/${{ env.IMAGE_PREFIX }}/${{ matrix.container }}:main-amd64 \
            ${{ env.REGISTRY }}/${{ env.IMAGE_PREFIX }}/${{ matrix.container }}:main-arm64
